name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Use Node.js 20
        run: |
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
          npm install -g npm@latest

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Test Docker image
        run: docker run my-node-app npm test
